### ISSUE TITLE
Crear el UI Layout

### ISSUE THREAD

**Issue by jruiz26lab** [josebecerra18/web_temp#1]
Crear el UI Layout según la imagen.
-   El Feeds.tsx tiene que mantener su ancho durante todo el tiempo.
<img width="780" alt="image" src="https://github.com/josebecerra18/web_temp/assets/84398482/9b545858-236a-450a-ac57-e1c3086ddafc">

**Comment by jruizu** [comment]
Tiempo estimado: 
2h.
Tiempo de entrega: 
Sabado 2 Marzo
