### ISSUE TITLE
Crear Card component

### ISSUE THREAD

**Issue by jruiz26lab** [josebecerra18/web_temp#3]
Continuar con el componente  Feeds.tsx con la DummyData.tsx.

<img width="502" alt="image" src="https://github.com/josebecerra18/web_temp/assets/84398482/3a21538e-4b26-4d26-ba0b-f2f0edc8497a">

**Comment by jruizu** [comment]
Tiempo estimado: 
2h.
Tiempo de entrega: 
Sabado 2 Marzo
